// pages/login/layout.tsx

import React from 'react';
import { ReactNode } from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

interface LayoutProps {
  children: ReactNode;
}
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Covoit’Ivoire",
  description: "Generated by Covoit’Ivoire",
};

const LoginLayout: React.FC<LayoutProps> = ({ children }) => {


  return (
    <html lang="en">
      <body className={inter.className}>
            <main>
                {children}
            </main>
        </body>
    </html>
  );
};

export default LoginLayout;
