// import { Sidebar } from "lucide-react"

import Sidebar from "../components/Sidebar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <div className="text-gray-800 font-inter">
            <Sidebar />
            {children}
            </div>
        </body>

    </html>
  )
}
